import "./help/help.ts";
import "./add-dependency-dialog/add-dependency-dialog.ts";
import "./edit-resources-dialog/edit-resources-dialog.ts";
import "./selected-task-panel/selected-task-panel.ts";
import "./simulation-panel/simulation-panel.ts";
import "./search/search-task-panel.ts";
import "./search/task-search-controls.ts";
import "./dependencies/dependencies-panel.ts";
import "./explanMain/explanMain.ts";
